name: Bug
description: Signaler un comportement incorrect
title: "[BUG] "
labels:
  - bug
body:
  - type: textarea
    id: context
    attributes:
      label: Contexte
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes de reproduction
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Résultat attendu
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Résultat observé
    validations:
      required: true
